import { GetProducts } from "./GetProducts.js";
import { login } from "./login.js";
import { Register } from "./Register.js";
import { GetFavorites } from "./GetFavorites.js";
import { GetWhishlist } from "./Getwhishlist.js";
GetProducts();
Register();
GetFavorites();
login();
GetWhishlist();
